export type ToolDefinition = {
  slug: string;
  name: string;
  description: string;
  badge: string;
  category: string;
};

export const tools: ToolDefinition[] = [
  { slug: "uuid", name: "UUID Generator", description: "Create v4 UUIDs instantly and copy a fresh batch for IDs, tests, and fixtures.", badge: "Identity", category: "Identity" },
  { slug: "bitmask-calculator", name: "Bitmask Calculator", description: "Set, clear, toggle, and inspect register bits across 8, 16, and 32-bit values.", badge: "Embedded", category: "Embedded" },
  { slug: "integer-ranges", name: "Integer Type Ranges", description: "Reference min and max values for common fixed-width signed and unsigned C integer types.", badge: "Embedded", category: "Embedded" },
  { slug: "endianness-converter", name: "Endianness Converter", description: "Flip byte order between big-endian and little-endian representations.", badge: "Embedded", category: "Embedded" },
  { slug: "crc-calculator", name: "CRC Calculator", description: "Calculate CRC-8, CRC-16 Modbus, and CRC-32 checksums for embedded payloads.", badge: "Embedded", category: "Embedded" },
  { slug: "struct-padding", name: "Struct Padding Visualizer", description: "Estimate offsets, alignment, and padding for common fixed-width fields in C structs.", badge: "Embedded", category: "Embedded" },
  { slug: "uart-baud-calculator", name: "UART Baud Calculator", description: "Estimate baud register divisors, actual baud rates, and error percentages.", badge: "Embedded", category: "Embedded" },
  { slug: "memory-viewer", name: "Memory Viewer", description: "Inspect raw hex bytes as offsets, grouped hex, and printable ASCII.", badge: "Embedded", category: "Embedded" },
  { slug: "ascii-hex-byte", name: "ASCII Hex Byte Converter", description: "Convert strings into byte values, hex bytes, and C-friendly representations.", badge: "Embedded", category: "Embedded" },
  { slug: "c-escape-generator", name: "C Escape Generator", description: "Turn text into escaped C string literals or explicit hex escape sequences.", badge: "Embedded", category: "Embedded" },
  { slug: "c-array-generator", name: "C Array Generator", description: "Generate const uint8_t arrays from sample text for firmware source files.", badge: "Embedded", category: "Embedded" },
  { slug: "fixed-point-converter", name: "Fixed-Point Converter", description: "Convert decimal values into scaled fixed-point integers using configurable Q formats.", badge: "Embedded", category: "Embedded" },
  { slug: "timer-prescaler", name: "Timer Prescaler Calculator", description: "Estimate timer tick periods, interrupt intervals, and resulting frequencies.", badge: "Embedded", category: "Embedded" },
  { slug: "can-frame-helper", name: "CAN Frame Helper", description: "Inspect simple CAN ID, frame type, DLC, and data byte layouts.", badge: "Embedded", category: "Embedded" },
  { slug: "modbus-rtu-helper", name: "Modbus RTU Helper", description: "Assemble simple Modbus RTU frames and append the correct CRC bytes.", badge: "Embedded", category: "Embedded" },
  { slug: "spi-i2c-cheatsheet", name: "SPI I2C Cheatsheet", description: "Reference SPI modes, convert I2C addresses, and estimate practical pull-up values.", badge: "Embedded", category: "Embedded" },
  { slug: "logic-level-converter", name: "Logic Level ADC DAC Converter", description: "Translate voltages into ADC counts and back using your selected reference.", badge: "Embedded", category: "Embedded" },
  { slug: "embedded-unit-converter", name: "Embedded Unit Converter", description: "Convert between Hz, kHz, MHz and ns, us, ms for common firmware calculations.", badge: "Embedded", category: "Embedded" },
  { slug: "float-inspector", name: "IEEE-754 Float Inspector", description: "Inspect a float as hex plus its sign, exponent, and mantissa fields.", badge: "Embedded", category: "Embedded" },
  { slug: "twos-complement", name: "Two's Complement Converter", description: "Interpret integer values as signed, unsigned, binary, and hex across common widths.", badge: "Embedded", category: "Embedded" },
  { slug: "c-preprocessor-eval", name: "C Preprocessor Expression Evaluator", description: "Evaluate macro-style numeric expressions with shifts, masks, and arithmetic.", badge: "Embedded", category: "Embedded" },
  { slug: "register-field-builder", name: "Register Field Builder", description: "Pack and extract bitfields by offset and width while seeing masks and shifted values immediately.", badge: "Embedded", category: "Embedded" },
  { slug: "pll-calculator", name: "PLL Calculator", description: "Estimate VCO and final output clocks while exploring pre-dividers, multipliers, and post-dividers.", badge: "Embedded", category: "Embedded" },
  { slug: "dma-throughput-calculator", name: "DMA Throughput Calculator", description: "Estimate burst count, cycle overhead, transfer time, and throughput for DMA moves.", badge: "Embedded", category: "Embedded" },
  { slug: "intel-hex-inspector", name: "Intel HEX Inspector", description: "Parse Intel HEX firmware records, inspect absolute addresses, and catch checksum errors.", badge: "Embedded", category: "Embedded" },
  { slug: "s-record-inspector", name: "S-Record Inspector", description: "Decode Motorola S-record files, inspect addresses, and validate record checksums.", badge: "Embedded", category: "Embedded" },
  { slug: "base64", name: "Base64 Encoder", description: "Encode or decode text with UTF-8 support without leaving the browser.", badge: "Encoding", category: "Encoding" },
  { slug: "calculator", name: "Calculator", description: "A quick arithmetic workspace with keyboard-friendly buttons and running evaluation.", badge: "Math", category: "Math" },
  { slug: "hex-calculator", name: "Hex Calculator", description: "Convert between decimal, hexadecimal, binary, and octal while keeping everything in sync.", badge: "Number Systems", category: "Math" },
  { slug: "json-formatter", name: "JSON Formatter", description: "Validate, prettify, and minify JSON with clear error feedback for malformed input.", badge: "Data", category: "Data" },
  { slug: "json-diff", name: "JSON Diff", description: "Compare two JSON documents side by side and quickly spot structural or value changes.", badge: "Data", category: "Data" },
  { slug: "json-to-typescript", name: "JSON to TypeScript", description: "Turn sample JSON into a fast starter TypeScript type definition.", badge: "Data", category: "Data" },
  { slug: "url-encoder", name: "URL Encoder", description: "Encode and decode URLs, query strings, and reserved characters for safer sharing.", badge: "Encoding", category: "Encoding" },
  { slug: "url-parser", name: "URL Parser", description: "Break down a URL into protocol, host, path, parameters, and fragment parts instantly.", badge: "Encoding", category: "Encoding" },
  { slug: "query-param-editor", name: "Query Param Editor", description: "Build and edit URLs with query parameters without hand-editing long strings.", badge: "Encoding", category: "Encoding" },
  { slug: "mqtt-client", name: "MQTT Client", description: "Connect to MQTT brokers over WebSockets, subscribe to topics, publish messages, and inspect traffic in the browser.", badge: "Network", category: "Network" },
  { slug: "timestamp-converter", name: "Timestamp Converter", description: "Move between Unix timestamps and readable dates with UTC and local time views.", badge: "Time", category: "Data" },
  { slug: "cron-parser", name: "Cron Parser", description: "Read a cron expression field by field so schedules become easier to verify.", badge: "Time", category: "Data" },
  { slug: "hash-generator", name: "Hash Generator", description: "Generate SHA hashes in the browser for quick integrity checks and comparisons.", badge: "Identity", category: "Security" },
  { slug: "tls-key-generator", name: "TLS Key Generator", description: "Generate RSA keypairs and symmetric secrets directly in the browser, with PEM and raw encodings.", badge: "Security", category: "Security" },
  { slug: "certificate-inspector", name: "Certificate Inspector", description: "Parse PEM certificates to inspect issuer, subject, SANs, validity, key usage, and fingerprint values.", badge: "Security", category: "Security" },
  { slug: "csr-generator", name: "CSR Generator", description: "Generate a private key and certificate signing request with subject and SAN fields.", badge: "Security", category: "Security" },
  { slug: "jwt-decoder", name: "JWT Decoder", description: "Inspect JWT headers and payloads locally, with readable expiry and issue times.", badge: "Security", category: "Security" },
  { slug: "case-converter", name: "Case Converter", description: "Flip text between camelCase, PascalCase, snake_case, kebab-case, and more.", badge: "Text", category: "Text" },
  { slug: "regex-tester", name: "Regex Tester", description: "Test expressions against sample text, review flags, and inspect captured matches.", badge: "Text", category: "Text" },
  { slug: "html-entities", name: "HTML Entity Tool", description: "Encode text into HTML entities or decode escaped markup back into readable text.", badge: "Encoding", category: "Encoding" },
  { slug: "text-diff", name: "Text Diff", description: "Compare two blocks of text line by line and spot changed, added, or removed content.", badge: "Text", category: "Text" },
  { slug: "lorem-generator", name: "Lorem Generator", description: "Generate placeholder paragraphs, sentences, and words for UI mocks and demos.", badge: "Content", category: "Content" },
  { slug: "http-status", name: "HTTP Status Lookup", description: "Search common HTTP response codes and read what they mean in practice.", badge: "Reference", category: "Reference" },
  { slug: "mime-lookup", name: "MIME Lookup", description: "Look up common file extensions and MIME types for headers, uploads, and assets.", badge: "Reference", category: "Reference" },
  { slug: "color-converter", name: "Color Converter", description: "Convert hex colors into RGB and HSL with a live swatch preview.", badge: "Design", category: "Design" },
  { slug: "color-contrast", name: "Color Contrast Checker", description: "Check foreground and background combinations against WCAG contrast thresholds.", badge: "Design", category: "Design" }
];
